services:
  app:
    build: .
    container_name: parcelpro-php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=parcelpro
      - DB_USERNAME=parcelpro
      - DB_PASSWORD=parcelpro

  nginx:
    image: nginx:alpine
    container_name: parcelpro-nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8
    container_name: parcelpro-mysql
    environment:
      MYSQL_DATABASE: parcelpro
      MYSQL_USER: parcelpro
      MYSQL_PASSWORD: parcelpro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: